version: "3.9"

services:
  lab:
    image: elec3210-lab
    build:
      context: docker/lab
      dockerfile: lab.dockerfile
    restart: no
    privileged: true
    ports:
      - "3210:3210"

    environment:
      - DISPLAY=:10.0
      - PORT=3210
    volumes:
      - ${APP_PATH}:/ws/src/app
      - ${DATA_PATH}:/ws/src/dataset
    tty: true